### ISSUE TITLE
knowledge issue

### ISSUE THREAD

**Issue by MerlinPeter** [mike4aday/SwiftlySalesforce#103]
We are in the process of submitting the iOS app for app store review ,   apple is asking for a demo username and password , salesforce is trying to verify the identity because they are logging in from a new host /device apple has rejected the app in that scenario . They want to just pass the username and password and get into the app . I searched in the knowledge base of salesforce to get around there is no chance and saleforce enforces this policy strictly . How did you guys manage this situation 
I understand this is not related to this library but this is the best place to ask because you have travelled the same path before.

thanks

**Comment by mike4aday** [comment]
@MerlinPeter in Salesforce, you can whitelist the IP addresses from which Apple is likely to test your app. Then Salesforce will not require an activation code. 

In Salesforce:

1) Go to Setup -> Users -> Users -> [The user you designated for Apple testers] -> Login History
Note the IP address from which they tried; their attempt will be logged with status of "Failed: Computer activation required"

2) Go to Setup -> Security -> Network Access
Add this IP range: 17.0.0.0 to 17.255.255.255
If the IP address in no. 1 above is not in this range, add another range that includes that IP address

**Comment by MerlinPeter** [comment]
thanks much please close the knowledge issue
