### ISSUE TITLE
Login with username password without the salesforce web-UI

### ISSUE THREAD

**Issue by tychop** [mike4aday/SwiftlySalesforce#104]
I need to login to salesforce with application specific credentials.
Therefor, I need to login from within the app.
Is this possible in SwiftlySalesforce?
I think I can get a token by logging in via a POST request, but can I inject that token somewhere into SwiftlySalesforce so it actually uses it?

**Comment by mike4aday** [comment]
@tychop - Swiftly Salesforce is designed only for the recommended [OAuth user-agent flow](https://help.salesforce.com/articleView?id=remoteaccess_oauth_user_agent_flow.htm&type=5), which temporarily redirects the user to the Salesforce-hosted login form and then back with an access token. (It's a security risk for mobile apps to handle or store the Salesforce username and password.)
