### ISSUE TITLE
Timeout interval

### ISSUE THREAD

**Issue by auctifera-josed** [mike4aday/SwiftlySalesforce#105]
Is there any way to modify the timeoutInterval of the URLRequest struct?

I've some APEX rest services that defaults to the maximum timeout (2 mins) and the app defaults to 1 min, I've edited the RESTResource.swift that extends RESTResource and set `req.timeoutInterval = 140` (just to give it a few more seconds than 2 mins) but I guess this could be a useful feature.

**Comment by mike4aday** [comment]
Thanks @auctifera-josed -- this is a great idea. I'll mark it as an 'enhancement.'

**Comment by mike4aday** [comment]
@auctifera-josed this is delivered in version 8.0. You can now provide your own `URLSession` to any request and set the timeout interval - and lots of other properties via [URLSessionConfiguration](https://developer.apple.com/documentation/foundation/urlsessionconfiguration).

See [RequestConfig](https://github.com/mike4aday/SwiftlySalesforce/blob/master/Sources/SwiftlySalesforce/Salesforce.swift#L33) struct, and how it can be used, for example, in [Salesforce.identity(config:)](https://github.com/mike4aday/SwiftlySalesforce/blob/master/Sources/SwiftlySalesforce/Salesforce.swift#L74).
