### ISSUE TITLE
Example for insert a lead with custom fields

### ISSUE THREAD

**Issue by DanielsCode** [mike4aday/SwiftlySalesforce#108]
Hi @mike4aday,

thanks for this framework. Do you have a short example for inert a record (like a lead with custom fields?). I didn't find any example code in your documentation. 

thanks,
daniel

**Comment by mike4aday** [comment]
Hi @DanielsCode - inserting a record would be very similar to the [update record example](https://github.com/mike4aday/SwiftlySalesforce#example-update-a-salesforce-record), except you'd use one of the insert methods (see lines 60-88 in the [source code](https://github.com/mike4aday/SwiftlySalesforce/blob/master/SwiftlySalesforce/Sources/Extensions/Salesforce%2BSObject.swift)). For example:

```swift
salesforce.insert(type: "Lead", fields: ["MyCustomField__c": "A Custom Value"])
.done { (id) -> () in
    // Update the local model
}.finally {
    // Update the UI
}
```

I just include 1 custom field above as an example - you'd have to also add any required fields that don't have default values.

**Comment by mike4aday** [comment]
@DanielsCode closing this issue - if you still have questions, please re-open.
