### ISSUE TITLE
Support for TLS 1.1?

### ISSUE THREAD

**Issue by elliottbolzan** [mike4aday/SwiftlySalesforce#11]
This is more of a question than issue: does SwiftlySalesforce support the switch to TLS 1.1 that Salesforce is pushing through? If so, since what version of SwiftlySalesforce is the case? I'm trying to determine whether I need to rebuild (and perhaps modify) an app that was built on SwiftlySalesforce this summer. Thank you!

**Comment by mike4aday** [comment]
Hi @elliottbolzan - yes, Swiftly Salesforce supports Salesforce's move to TLS 1.1, and has since the first version, so no re-build necessary.

You can confirm that your existing app will work with TLS 1.1 per this article:
https://help.salesforce.com/apex/HTViewSolution?id=000221207
