### ISSUE TITLE
Login screens - Dark mode support

### ISSUE THREAD

**Issue by perbrondum** [mike4aday/SwiftlySalesforce#110]
Is there an easy way to get the two default login screens set to Dark Mode?

**Comment by mike4aday** [comment]
@perbrondum not as far as I know. The login form and access approval screens are hosted by Salesforce and there is no [setting](https://help.salesforce.com/articleView?id=remoteaccess_oauth_user_agent_flow.htm&type=5) for dark mode - that would be a great [idea](https://success.salesforce.com/ideaSearch).
