### ISSUE TITLE
Login screen not being shown with SwiftUI

### ISSUE THREAD

**Issue by KalivosGG** [mike4aday/SwiftlySalesforce#112]
Hi, I just found out this repo as an alternative to the iOS salesforce sdk, I followed the setup example and didn't succeed. 
My question is: should the library be calling the login screen (webview) at any moment after setting the the salesforce variable?
Is there any way to use it without SwiftUI?

**Comment by mike4aday** [comment]
@KalivosGG Swiftly Salesforce should work with and without SwiftUI. You don't have to display the login screen explicitly; it will appear automatically if the framework can't retrieve an access token from the local keychain, or refresh it from Salesforce. Would you post some representative code that will help me identify what might be going wrong?

**Comment by KalivosGG** [comment]
@mike4aday Hey I finally managed to work it out, I was trying to retrieve data right after setting salesforce and I was getting no error or messages at all. I added a delay to retrieve some records and it worked!

Now I'm getting "server cannot be found" when trying to login.

**Comment by mike4aday** [comment]
Hi @KalivosGG - the login sequence uses Apple's prescribed [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession). You could add a debug breakpoint in the [authenticator method in the UserAgentFlow class](https://github.com/mike4aday/SwiftlySalesforce/blob/master/Sources/SwiftlySalesforce/UserAgentFlow.swift#L19).

You shouldn't need to add a delay to retrieve records. Once you call a method on the `salesforce` instance and attach a Combine subscriber, the subscriber's closure will be called when the results are returned.

**Comment by KalivosGG** [comment]
@mike4aday thank you very much, I'll look into it.

**Comment by mike4aday** [comment]
Hi @KalivosGG I'll close this issue for now. If you have more questions or it's not resolved, please re-open or create a new issue.
