### ISSUE TITLE
misspelled function

### ISSUE THREAD

**Issue by perbrondum** [mike4aday/SwiftlySalesforce#113]
let pub: AnyPublisher<Void, Error> = salesforce.logout() 
should be
let pub: AnyPublisher<Void, Error> = salesforce.logOut()

**Comment by mike4aday** [comment]
Thanks @perbrondum - I'll take care of this soon.

**Comment by mike4aday** [comment]
Fixed in version 8.0.1 (pull request #122).
Thank you @perbrondum
