### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by mike4aday** [mike4aday/SwiftlySalesforce#12]

**Comment by biskit** [comment]
+1

**Comment by mike4aday** [comment]
Thanks @biskit - I'm not familiar with Carthage, so I've been procrastinating on this one. I'll bump it up the priority list to get Carthage support added.

**Comment by mike4aday** [comment]
Carthage support added with release of version 3.3.2

@biskit FYI

**Comment by biskit** [comment]
thankyou!  👏
