### ISSUE TITLE
Logout is failing

### ISSUE THREAD

**Issue by camiloduqued** [mike4aday/SwiftlySalesforce#120]
I'm having issues with the logout since I updated Swiftly Salesforce to version 8.0.0, I added the package with the Swift Package Manager and updated the implementation to the Combine framework. Sometimes it fails and sometimes it's successful.

When it fails the request made at the OAuthManager revoke function responds with a status 404 and the body (data) is "Bad_Id".

It's weird because that error is not supposed to be sent at the revoke endpoint, so the code maps it to an OAuthManagerError.endpointFailure with code "Unknown".

![image](https://user-images.githubusercontent.com/26864817/85051885-b2ea5d00-b15d-11ea-9785-24e1cc988ebc.png)

The request URL and the body are fine, I even tried to make the same request separately (but using query parameters instead of body) with the same token and it was successful. I think this was a coincidence because I edited the code to use query parameters and it's still failing.

**Comment by mike4aday** [comment]
Thanks @camiloduqued - I've not seen this before and will try to figure out what's going on. Were you able to see if the token was revoked on the Salesforce side?

**Comment by camiloduqued** [comment]
No @mike4aday, the token was not revoked, even as it fails the user is not removed from the User Defaults, so when I try to login again, it skips the Salesforce Login and all the subsequent requests are successful.

**Comment by mike4aday** [comment]
Thanks @camiloduqued - I'll look into this.

**Comment by mike4aday** [comment]
Hi @camiloduqued - which OAuth scopes did you select in your Connected App definition?

**Comment by camiloduqued** [comment]
Hi @mike4aday, I selected these scopes: 
![image](https://user-images.githubusercontent.com/26864817/85349130-422ba380-b4c3-11ea-9c8f-229ce2b49739.png)

**Comment by mike4aday** [comment]
Hi @camiloduqued - I'm still checking into this. As you noted, 404 and "Bad_Id" is not documented as a possible result of a call to the OAuth 'revoke' endpoint. Back to you soon.

**Comment by mike4aday** [comment]
@camiloduqued - I asked experts at Salesforce and so far the only possible explanation is that the request to the 'revoke' endpoint is coming from an 'invalid domain.' Are you able to provide a trace route of the path from the caller to the 'revoke' endpoint? Approximately how often do you see the failure (as % of all calls to revoke)? I've not been able to replicate the issue.

**Comment by mike4aday** [comment]
@camiloduqued I'll close this for now; re-open if needed.
