### ISSUE TITLE
Login not working after dismissed

### ISSUE THREAD

**Issue by auctifera-josed** [mike4aday/SwiftlySalesforce#124]
Hi everyone, some users are experiencing an issue with the login if they dismissed it by tapping outside the view controller (if they tap in the cancel button there is no problem)

We have a "Log in" button that calls the following code

```swift
salesforce.identity(config: .shared)
.receive(on: DispatchQueue.main)
.sink(receiveCompletion: { (uCompletion) in
    ///stuff
}, receiveValue: { (userInfo : Identity) in
    ///stuff
}).store(in: &cancellables)
```

Then the salesforce login is presented in a modal which works fine, but if the user taps outside the modal the login modal is dismissed and there is no way of presenting the login view again

![IMG_210C282AA8A6-1](https://user-images.githubusercontent.com/16018027/94091420-cbfa4e00-fddd-11ea-877e-2f942bb81194.jpeg)

I thought that maybe canceling the cancelable would help but it didn't

```swift
var loginCancelable: AnyCancellable?
    
func login(){
    if let loginCancelable = loginCancelable {
        loginCancelable.cancel()
    }
    
    loginCancelable = salesforce.identity(config: config)
    ...
}
```

Even tried reinitializing the `salesforce` property before calling the `identity`

```swift
...
salesforce = Salesforce(connectedApp: connectedApp, oAuthHostname: oauthHostName)
loginCancelable = salesforce.identity(config: config)
...

```

Does anyone have an idea what's going on here? Or maybe just how can we present the login modal in full screen so they can't tap outside?

**Comment by mike4aday** [comment]
@auctifera-josed - I did try to capture the tap outside the login form gesture, but didn't succeed. Seems to be a limitation of Apple's prescribed authentication mechanism using [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession).

Another idea I had but haven't had time yet to prototype: Salesforce allows you to specify a different form factor for the login form - see the `display` parameter at [this link](https://help.salesforce.com/articleView?id=remoteaccess_oauth_user_agent_flow.htm&type=5). Swiftly Salesforce currently uses `touch` -- maybe `page` offers a larger display which, if accommodated by ASWebAuthenticationSession, would make it less likely that the user clicks outside the bounds of the login form?
