### ISSUE TITLE
Question: Best practices for querying if user is allowed to update object

### ISSUE THREAD

**Issue by perbrondum** [mike4aday/SwiftlySalesforce#125]
I can try to update object and fail, but was hoping for a better way.

**Comment by mike4aday** [comment]
Hi @perbrondum - you can call the `describe` method [here](https://github.com/mike4aday/SwiftlySalesforce/blob/e5063a32178ded9269cb87dbdbc77940498d1f71/Sources/SwiftlySalesforce/Salesforce%2BDescribe.swift#L20), and the boolean `isUpdateable` property will tell you whether the current user can update the record.
