### ISSUE TITLE
MyRecords() func assumes object has 'ownerId' column

### ISSUE THREAD

**Issue by perbrondum** [mike4aday/SwiftlySalesforce#128]
If the new MyRecords is to be used across objects it should not use 'ownerid' in predicate.

**Comment by mike4aday** [comment]
Hi @perbrondum not sure I understand your objection. [`myRecords`](https://github.com/mike4aday/SwiftlySalesforce/blob/cf4becddd63d1a4a6900da5ec3afd0fd87401b0b/Sources/SwiftlySalesforce/ConnectedApp%2BQuery.swift#L64) is meant to be a convenience method: callers don't have to know the logged-in user's ID, and the `OwnerId` is present on [most objects](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_fequently_occurring_fields.htm). If `myRecords` were to be called with a type that doesn't have an `OwnerId` field, the publisher will fail with an error. In such cases, it's always possible to write a custom SOQL query for a particular object using the [`query`](https://github.com/mike4aday/SwiftlySalesforce/blob/cf4becddd63d1a4a6900da5ec3afd0fd87401b0b/Sources/SwiftlySalesforce/ConnectedApp%2BQuery.swift#L22) method instead.

**Comment by mike4aday** [comment]
@perbrondum I'll add a note to the documentation so it's more explicit that the `type` argument has to be for an SObject type that does have the `ownerId` field.

**Comment by perbrondum** [comment]
Good points. We always use createdById (unless in object sharing mode) as
all objects have them and it has no ambiguity. OwnerId has implications for
delegation and makes assumptions on account model that are more complex and
as such most implementations have ownerId = createdById.

Per B Jakobsen
CEO  Tap2Sales.com
***@***.***

**Comment by mike4aday** [comment]
@perbrondum Cases and Accounts, for example, are routinely reassigned after creation and then would have CreatedById != OwnerId no?

**Comment by perbrondum** [comment]
Exactly.

Per

**Comment by mike4aday** [comment]
@perbrondum I don't understand - if I'm interested in querying records I own, e.g. cases or accounts for which I'm responsible, and regardless of who or what process originally created the records, then querying for records where my user ID equals the records' CreatedById wouldn't work, no?

**Comment by perbrondum** [comment]
Correct.  OwnerId was added to denote assignment or delegation.  So, in
account sharing mode, the owner creates events with createdById !=
ownerId.  No disagreement here.

My original objection was that ownerId was added to a func that accepts all
object types.

Per B Jakobsen
CEO  Tap2Sales.com
***@***.***

**Comment by mike4aday** [comment]
@perbrondum thanks. I added a note to the documentation that the method is for types with `OwnerId` field and reference to docs.
