### ISSUE TITLE
salesforce.search() replacement? in 9.0

### ISSUE THREAD

**Issue by perbrondum** [mike4aday/SwiftlySalesforce#134]
Is there a replacement for .search(sosl:) in 9.0.5

**Comment by mike4aday** [comment]
@perbrondum no, I haven't had the chance yet to create an 'out of box' search method in Swiftly Salesforce v9. You could create your own search capability relatively easily: create a custom struct that implements the `Service` protocol -- see [QueryService](https://github.com/mike4aday/SwiftlySalesforce/blob/60c9506808b3c4e62f5f1cbfbd9c6e8061458315/Sources/SwiftlySalesforce/Services/QueryService.swift), [SObjectsService](https://github.com/mike4aday/SwiftlySalesforce/blob/60c9506808b3c4e62f5f1cbfbd9c6e8061458315/Sources/SwiftlySalesforce/Services/SObjectsService.swift), or [LimitsService](https://github.com/mike4aday/SwiftlySalesforce/blob/60c9506808b3c4e62f5f1cbfbd9c6e8061458315/Sources/SwiftlySalesforce/Services/LimitsService.swift) as examples.

**Comment by perbrondum** [comment]
Ok, thanks. 

Per
