### ISSUE TITLE
keyNotFound "id" error on simple query

### ISSUE THREAD

**Issue by perbrondum** [mike4aday/SwiftlySalesforce#137]
// Fails in 9.06 BETA with:

keyNotFound(CodingKeys(stringValue: "Id", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "records", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"Id\", intValue: nil) (\"Id\").", underlyingError: nil))

when using <USER>, works when using <SalesforceRecord>. 

Not blocking for me, but seems related to the fix somehow.

```
private func getSFDCData() {
    DB.salesforce.identity().sink(receiveCompletion: { (completion) in
        switch completion {
        case .finished:
            break
        case let .failure(error) :
            print("Failed to login. Error: \(error)")
        }
    }) { identity in
        let userId = identity.userID
        
        let userSoql = "SELECT CompanyName FROM User where id = '\(userId)'"
        DB.salesforce.query(soql: userSoql).sink(receiveCompletion: { (completion) in
            switch completion {
            case let .failure(error):
                print("Failed to query(1) SFDC in MeetingVC. Error: \(error)")
            case .finished:
                break
            }
        }, receiveValue: { (userData : QueryResult<User>) in
            //
        }).store(in: &subscriptions)
    }.store(in: &subscriptions)
}
```

**Comment by perbrondum** [comment]
line 5: Should read "fails when using USER struct, works when using SALESFORCERECORD"

**Comment by mike4aday** [comment]
@perbrondum I believe the issue is that the "Id" field is not in the list of queried fields in your SOQL query; only `CompanyName` is queried. Does it work if you add `Id` to the queried field list?

**Comment by perbrondum** [comment]
Sorry, just saw this. While id is not needed in the select list, I will check tomorrow if the bug still exists with it in.

**Comment by mike4aday** [comment]
Hi @perbrondum - I assume `User` is a custom model struct you defined? If so, then any property defined as optional will work since the automatic decoding provided by Swiftly Salesforce via Swift's `Decodable` protocol will not throw an error if the server response is missing a value for that property. If the property is required, however, then it must be present in the JSON response, and the relevant field has to be in the `SOQL` select list.

**Comment by perbrondum** [comment]
Makes sense.  Thanks for looking into this.

Per B Jakobsen
CEO  Tap2Sales.com
***@***.***
