### ISSUE TITLE
Documentation on salesforce.insert incorrectly mandates 'Id' as input field

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#15]
See salesforce.swift (look for insert). Id should not be part of the call.

Router.insert correctly states the API without 'Id'.

**Comment by mike4aday** [comment]
Fixed in version 3.1.1

**Comment by mike4aday** [comment]
Thank you, @pbrondum - should be corrected in newly-released version 3.1.1
