### ISSUE TITLE
Question. Will this work with the Chatter API

### ISSUE THREAD

**Issue by helloniklas** [mike4aday/SwiftlySalesforce#17]
HI, I'm new to Salesforce. Is SwiftlySalesforce something that will work with the Chatter API? Or is that a whole different API.

**Comment by mike4aday** [comment]
Hi @helloniklas - Yes, Swiftly Salesforce will work with the Chatter API. 

There's not currently a Chatter-specific method for interacting with Chatter API resources, so you can use the generic Salesforce.custom( ) method (see line 176 in [Salesforce.swift](https://github.com/mike4aday/SwiftlySalesforce/blob/master/Pod/Classes/Salesforce.swift)).

For example: to retrieve a user's Chatter profile info:

```swift
// Retrieve Chatter profile info for user by user ID 
salesforce.custom(path: "/services/data/v37.0/chatter/users/005i00000016BdfAAE")
```

**Comment by mike4aday** [comment]
@helloniklas BTW there's a great tool for working with Salesforce APIs, including the Chatter API: [Workbench](https://workbench.developerforce.com)

See especially Workbench's [REST Explorer](https://workbench.developerforce.com/restExplorer.php)

**Comment by helloniklas** [comment]
Brilliant, all works thanks very much. Was trying the apexRest earlier...
