### ISSUE TITLE
How to use SFPushNotificationManager in Swiftly

### ISSUE THREAD

**Issue by helloniklas** [mike4aday/SwiftlySalesforce#18]
So I'm able to send a test push to the device from the Salesforce console... However, I believe I'm meant to use the SFPushNotificationManager to get the device token into the User object in salesforce. 

Is SFPushNotificationManager not available in SwiftlySalesforce. Will I have to use and auth with the SalesforceMobileSDK-iOS in order to do this?

**Comment by mike4aday** [comment]
@helloniklas Swiftly Salesforce doesn't (yet) support push notifications. I'd welcome a pull request adding push notification support :-)

**Comment by mike4aday** [comment]
@helloniklas have you already seen this: https://developer.salesforce.com/docs/atlas.en-us.pushImplGuide.meta/pushImplGuide/pns_using_chatter_rest_api.htm

**Comment by helloniklas** [comment]
@mike4aday I did read through that, but what I'm after is being able to push out from Salesforce Chatter to devices when say a new post is made to a group. That seems to be more for sending from device to device.

Is there a manual way to save the device push token on the User object, or the Chatter User? With out using the whole SFPushNotificationManager?

**Comment by mike4aday** [comment]
@helloniklas I've not worked with push notifications on the platform - what is the name of the field where you'd save the push token? You could use Swiftly Salesforce to update a field on the User object, or any object & field, for which the logged in user has update permission:

```swift
salesforce.update("User", id: "USER_ID", fields: ["fieldName": "token"])
```

**Comment by helloniklas** [comment]
Thanks, will look into it. Looking at their SDK it seems they're calling services/data/v36.0/sobjects/MobilePushServiceDevice 
sending
`NSDictionary* bodyDict = @{@"ConnectionToken":_deviceToken, @"ServiceType":@"Apple"};`

**Comment by mike4aday** [comment]
@helloniklas you could use the `Salesforce.custom` method to call that:

```swift
let path = "services/data/v36.0/sobjects/MobilePushServiceDevice"
let params = ["ConnectionToken": deviceToken, "ServiceType":  "Apple"]
salesforce.custom(path: path, parameters: params)
```

If it's a POST request, set the `method` argument to `.post` (and you could use "v38.0" in the path to get the latest version of the resource, though it's likely unchanged since version 36.0)

Let me know if/how you get this to work and I'll update the framework to make it easier.

**Comment by auctifera-josed** [comment]
Hi @mike4aday, I'm implementing this and hopefully will send you a PR about it but I can't seem to find the `salesforce.custom` function, I guess this was removed in a more recent version. Is `salesforce.request` what I would use to reach this custom endpoint?

**Comment by auctifera-josed** [comment]
Nevermind, since `MobilePushServiceDevice` is a `sobjects` I was able to achieve this using the `salesforce.insert`

```swift
func registerForNotifications(with deviceToken: String) {
    var fields: [String : Encodable?] = ["ConnectionToken" : deviceToken]
    fields["ServiceType"] = "Apple"
    fields["ApplicationBundle"] = Bundle.main.bundleIdentifier
    
    salesforce.insert(object: "MobilePushServiceDevice", fields: fields)
    .sink(receiveCompletion: { (completion) in
        //TODO: handle completion
    }) { algo in
        //TODO: successfully updated
    }.store(in: &cancellables)
}
```

**Comment by mike4aday** [comment]
Thanks @auctifera-josed

**Comment by mike4aday** [comment]
@auctifera-josed BTW I will restore the push service registration function in an upcoming release so you don't have to write your own function that calls `insert`
