### ISSUE TITLE
Authorization Not Working

### ISSUE THREAD

**Issue by aparente99** [mike4aday/SwiftlySalesforce#19]
I am completely unsure why authorization is not working for me..

Not working with example app or my integrated app.

I am taken to the callbackURL, but then after that the safari view controller is not dismissed and the app does not retrieve the token.

**Comment by mike4aday** [comment]
@aparente99 did you register the callback URL's scheme with iOS?
See: https://github.com/mike4aday/SwiftlySalesforce#register-your-connected-apps-callback-url-scheme-with-ios

**Comment by aparente99** [comment]
Yes, this was the issue!

Thank you so much

**Comment by mike4aday** [comment]
@aparente99 You're very welcome!

**Comment by loopingGIT** [comment]
I am having the same problem I do have configured the info.plist but the callback is never captured.
I do get the permission request, and everything seems fine on SF
This is my info.plist
```
//my callback url
let redirectURL = URL(string: "https://www.mycustomurl.com")!

// I tried with this two options (the one on the docs and the one that comes on the example), separated and together.
// example
<dict>
     <key>CFBundleURLName</key>
     <string>SalesforceOAuth2</string>
     <key>CFBundleURLSchemes</key>
     <array>
	<string>mycustomurl</string>
     </array>
</dict>

//docs
<dict>
            <key>CFBundleURLName</key>
            <string>SalesforceOAuth2CallbackURLScheme</string>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>mycustomurl</string>
            </array>
</dict>
```

**Comment by jitesh95** [comment]
> customuri://callback-url.net

Hi, 

could you please give me screenshots of salesforce connected app and info.plist  file. I am trying this from last 2 days, still could authorize the app.

**Comment by loopingGIT** [comment]
@jitesh95 I am sorry, but I don't work in this project anymore and I don't have the code to take the screenshots.

**Comment by mike4aday** [comment]
Hi @jitesh95 - you don't need to register the scheme in the info.plist file anymore, thanks to changes Apple made.

**Comment by mike4aday** [comment]
@jitesh95 - and as mentioned in issue #115 you need to use a custom scheme that is *not* http or https.
