### ISSUE TITLE
Is it possible to read accessToken

### ISSUE THREAD

**Issue by knoppkirrie** [mike4aday/SwiftlySalesforce#21]
Hi,
is it possible to read the accessToken of my current session? I want to download a user's profile picture and need that token to retrieve the full photo url.
Thanks in advance

**Comment by mike4aday** [comment]
Hi @knoppkirrie - you could read the access token for the current session like this:
`let accessToken = salesforce.authManager.authData?.accessToken`

**Comment by knoppkirrie** [comment]
Thanks a lot, that was exactly what I was looking for.
