### ISSUE TITLE
Swift 3.0 conversion failing

### ISSUE THREAD

**Issue by tapdancemobile** [mike4aday/SwiftlySalesforce#23]
Hello, I am trying to get this to compile for a test project using XCode 8, Swift 3.0, and iOS 10. The pods are not compiling at the moment? 
<img width="490" alt="screen shot 2017-02-21 at 2 33 50 pm" src="https://cloud.githubusercontent.com/assets/298012/23181381/cdade292-f842-11e6-9ce8-e91c2ab37ae0.png">

**Comment by mike4aday** [comment]
Hi @tapdancemobile which version of Swiftly Salesforce are you using? What is the meaning of "Swift 3.0 conversion" in your issue title - i.e. what are you converting? Swiftly Salesforce v3.0+ works with Swift 3.0.

**Comment by mike4aday** [comment]
@tapdancemobile I'm closing this issue, but please re-open or continue to comment if you still need help.
