### ISSUE TITLE
salesforce.describe does not seem to handle multiple objects

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#25]
Example from README suggest that you can retrieve meta data for multiple objects.
"first {
  salesforce.describe(types: ["Account", "Contact", "Task", "CustomObject__c"])"

I can't get multiple objects to work.  Here's the func from Salesforce.swift, suggesting that only one object works:

open func describe(type: String) -> Promise<ObjectDescription> {
		let builder = {
			(authData: AuthData) throws -> URLRequest in
			return try Router.describe(type: type, authData: authData, version: self.version).asURLRequest()
		}
		let deserializer = {
			(response: [String: Any]) throws -> ObjectDescription in
			return ObjectDescription(json: response)
		}
		return request(requestBuilder: builder, jsonDeserializer: deserializer)
	}

**Comment by mike4aday** [comment]
@pbrondum the overloaded `describe` method at line 201 of [Salesforce.swift](https://github.com/mike4aday/SwiftlySalesforce/blob/master/Pod/Classes/Salesforce.swift) (and below) takes an array of Salesforce type to describe. Is that method not working for you? Which version of Swiftly Salesforce are you using? This method was added in version 3.3.0.

```Swift
open func describe(types: [String]) -> Promise<[ObjectDescription]> {
    let promises = types.map { describe(type: $0) }
    return when(fulfilled: promises)
}
```

**Comment by pbrondum** [comment]
I was on 3.2. Thanks.
