### ISSUE TITLE
Add method to download Contact photo

### ISSUE THREAD

**Issue by mike4aday** [mike4aday/SwiftlySalesforce#35]

**Comment by mike4aday** [comment]
Delivered in version 4.0.0. See `Salesforce.getImage` method.

**Comment by mike4aday** [comment]
For an example, see line 68:
https://github.com/mike4aday/SwiftlySalesforce/blob/master/Example/SwiftlySalesforce/MasterViewController.swift

**Comment by pbrondum** [comment]
salesforce.fetchImage(url: photoURL) works well for users and the example is great.
How would it work for Contacts?

**Comment by mike4aday** [comment]
@pbrondum did you figure out how to get contact photo? In short: retrieve a contact and its PhotoUrl field, then call Salesforce.fetchImage(path:) - (note that Contact.PhotoUrl is a relative path, not a complete URL).

**Comment by pbrondum** [comment]
I looked at the code and it was pretty straightforward. 

Thanks for adding all the enhancements

Per
