### ISSUE TITLE
Add method to get longitude/latitude for Contacts

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#38]

**Comment by mike4aday** [comment]
Delivered in version 4.0.0. See `Address` struct.

**Comment by pbrondum** [comment]
Michael -- Upgrading did not work for me.  I did 'pod upgrade swi...' and
it installed 4.0.  Suddenly Salesforce. functions are not recognized??

Thanks,

Per

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by mike4aday** [comment]
@pbrondum 4.0.0 is a 'breaking' release. Please see CHANGELOG.md. Which functions are no longer working?

**Comment by mike4aday** [comment]
@pbrondum the `salesforce` singleton has been removed in order to support multi-user switching and better practice. Your existing code will still work if you define a global variable in your AppDelegate file:

`var salesforce: Salesforce!`

See the first example in the README.md

**Comment by pbrondum** [comment]
Every function call fails with ‘Use of unresolved identifier ‘salesforce’.  Looks like a build issue.

Per

**Comment by pbrondum** [comment]
Ok - thanks. I'll add that!

Thanks for the quick reply.

Per

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by mike4aday** [comment]
@pbrondum in case our messages crossed paths: the `salesforce` singleton has been removed from SwiftlySalesforce, but you could declare your own, and your existing code should still work (except for a few changed method signatures, like `apex` instead of `apexREST`). See:

https://github.com/mike4aday/SwiftlySalesforce#example-configure-your-app-delegate

**Comment by pbrondum** [comment]
OK - that works.  I will look at the changelog file before I email you next
time!

Only error is in the old example code.

                        guard let userID = userInfo.userID else {

                            throw EventForceError.generic(code: 100,
message: "Can't determine user ID")

                        }

You eliminated that code in your example.  Would you replace the above or
fix it?

Thanks,

Per


Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by pbrondum** [comment]
Figured it out.

Thanks,

Per

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com


On Sat, Jul 15, 2017 at 10:01 AM, Per Brondum Jakobsen <perbrondum@gmail.com
