### ISSUE TITLE
Couldn't install using pod.

### ISSUE THREAD

**Issue by hmuronaka** [mike4aday/SwiftlySalesforce#4]
Hi, I tried to install SwiftlySalesforce 2.0.1 but I coudn't.
I think that the git-tag 2.0.1 does not exist. 

Thanks,

**Comment by mike4aday** [comment]
@hmuronaka sorry, I pushed the tag 2.0.1 now. Let me know if you're able to install Swiftly Salesforce.

**Comment by hmuronaka** [comment]
It worked - thank you!!
