### ISSUE TITLE
Build ERROR with Locksmith 3.0.0 Xcode 8.3.2

### ISSUE THREAD

**Issue by iandrosov** [mike4aday/SwiftlySalesforce#40]
Hello, I try adding SwiftlySalesforce to project pod file after opening generated workspace I see new dependencies been added. But build error with many syntax errors on Locksmith 3.0.0 framework looks like use of _  in function types and NSBundles. Seem Xcode like to add _ on functions? Any solutions for this?

Using Xcode 8.3.2 and Swift 3.1
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9

**Comment by mike4aday** [comment]
@iandrosov I'll check into this.

**Comment by mike4aday** [comment]
@iandrosov I was able to build ok; no errors with Locksmith. Are you building a macOS app?

**Comment by iandrosov** [comment]
My build target was iOS iPhone 7 on the simulator. The pod install worked fine and I can see all latest libraries. But when try to Build or run the app got unexpected syntax errors only on Locksmith. Other libs seem to be ok

**Comment by mike4aday** [comment]
@iandrosov Have you already tried quitting and restarting Xcode? Would you try with target of 10.0+ and see if that makes any difference? If not, would you post the version info from your Podfile.lock file?

**Comment by mike4aday** [comment]
@iandrosov I'll close this for now since I haven't heard back from you and I can't reproduce the issue. If the issue persists after restarting Xcode, please re-open and post the version info from your Podfile.lock file.
