### ISSUE TITLE
after login into salesforce how to redirect to the app ??

### ISSUE THREAD

**Issue by jvashisht** [mike4aday/SwiftlySalesforce#43]

**Comment by mike4aday** [comment]
@jvashisht There are 3 parts to that:

1) When you define your Connected App in Salesforce, choose a redirect URL with a custom protocol - *not* http or https. It doesn't matter what the URL is. For example: `myapp://go`

2)  Use that redirect URL in your Swift code, as shown in the example at: https://github.com/mike4aday/SwiftlySalesforce#example-configure-your-app-delegate

3) Register the URL scheme so iOS knows to launch your app upon redirect, as shown here:
https://github.com/mike4aday/SwiftlySalesforce#example-register-your-connected-apps-callback-url-scheme-with-ios
