### ISSUE TITLE
Error in Swift 4 host app

### ISSUE THREAD

**Issue by srinathp90** [mike4aday/SwiftlySalesforce#45]
App throws ''dyld: Library not loaded" error when host target kept as swift language version 4 and SwiftlySalesforce target kept in Swift 3 (in Xcode 9)

dyld: Library not loaded: @rpath/SwiftlySalesforce.framework/SwiftlySalesforce
  Referenced from: /Users/developer/Library/Developer/CoreSimulator/Devices/E8C812E3-D066-42B1-9577-831385897C76/data/Containers/Bundle/Application/6FCB02FF-4668-491B-AD97-7ECAD25B28D1/SwiftlySample.app/SwiftlySample
  Reason: no suitable image found.  Did find:
	/Users/developer/Library/Developer/CoreSimulator/Devices/E8C812E3-D066-42B1-9577-831385897C76/data/Containers/Bundle/Application/6FCB02FF-4668-491B-AD97-7ECAD25B28D1/SwiftlySample.app/Frameworks/SwiftlySalesforce.framework/SwiftlySalesforce: required code signature missing for '/Users/developer/Library/Developer/CoreSimulator/Devices/E8C812E3-D066-42B1-9577-831385897C76/data/Containers/Bundle/Application/6FCB02FF-4668-491B-AD97-7ECAD25B28D1/SwiftlySample.app/Frameworks/SwiftlySalesforce.framework/SwiftlySalesforce'

**Comment by mike4aday** [comment]
Thanks @srinathp90 - the framework hasn't been adapted to Swift 4 or Xcode 9 yet - pull requests welcome.

**Comment by mike4aday** [comment]
Swift 4.0 compatibility delivered in version 4.0.3
