### ISSUE TITLE
Can't make it running

### ISSUE THREAD

**Issue by andrey-manakov** [mike4aday/SwiftlySalesforce#46]
Hi,

Disclaimer, I am just learning. I couldn't run the SwiftlySalesforce. I managed to run example, but if I create a new project I just see a white screen of my storyboard. What I did: 
1. create a project
2. modified app delegate (like in example that working, so that should ok)
3. modified info.plist (like in example that working, so that should ok)
4. installed pods (pod install with pod file as specified)
5. installed carthage (as specified)

couldn't you help me? (attached the project)
[test7.zip](https://github.com/mike4aday/SwiftlySalesforce/files/1273322/test7.zip)

**Comment by mike4aday** [comment]
Hi @andrey-manakov I wasn't able to open the zip file, but maybe this will help:

Did you make a call to Salesforce? Until your code calls one of the methods in the `Salesforce` class, you'd only see your views. Once you make a call to Salesforce, and if there's not already a valid session token stored in the keychain, then Swiftly Salesforce will display the login form.

Also, you don't need both Carthage and Cocoapods (your steps 4 & 5) - just one or the other.

If this doesn't help, post your app delegate and the first view controller file.

Best regards

**Comment by pbrondum** [comment]
I was able to open the file.  Follow the README to add login code to the
ViewDidLoad in ViewController.swift.  Configure the consumer key in
AppDelegate.swift and set the proper values in the info.plist.

All documented in the README.

Per

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by mike4aday** [comment]
Thank you @pbrondum 

@andrey-manakov be sure you follow the steps shown in the README file at https://github.com/mike4aday/SwiftlySalesforce/blob/master/README.md

**Comment by andrey-manakov** [comment]
First of all thanks for prompt answer and clarification that I should choose pods or carthage. Meanwhile I checked again the instruction 

I couldn’t find the instruction of what should I implement in viewDidLoad of ViewController. In the example ViewController’s viewDidLoad looks just like this: 

	override func viewDidLoad() {
		super.viewDidLoad()
		refreshControl?.addTarget(self, action: #selector(MasterViewController.handleRefresh), for: UIControlEvents.valueChanged)
		loadData(refresh: true)
	}

Below the steps I made according to the readme. Still don’t work sorry to disturb you

Steps I made
1.	Create ios swift project
2.	Create pod file
target 'test8' do
  use_frameworks!
  pod 'SwiftlySalesforce'
end
3.	Run “pod install” in project dir

The result “Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.”

4.	Checked connected app I created earlier
5.	Modified AppDelegate

import UIKit
import SwiftlySalesforce
import UserNotifications

var salesforce: Salesforce!

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, UNUserNotificationCenterDelegate, LoginDelegate {
    
    let consumerKey = "3MVG96mGXeuuwTZi1FvcrlwfqoYjWRwuGR_6.W3Dllmu0T4B9rg.BjxLgIouC.b_YN.IMHFm7XhLrTWRLx.dh"
    let redirectURL = URL(string: "swiftapp://auth/success")!
    
    var window: UIWindow?
    
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        salesforce = Salesforce(connectedApp: ConnectedApp(consumerKey: consumerKey, redirectURL: redirectURL, loginDelegate: self))
        
        return true
    }
    
    func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey : Any] = [:]) -> Bool {
        handleRedirectURL(url, for: salesforce.connectedApp)
        return true
    }
}


6.	Modified info.plist

	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>SalesforceOAuth2</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>taskforce</string>
			</array>
		</dict>
	</array>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>salesforce.com</key>
			<dict>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludesSubdomains</key>
				<true/>
			</dict>
		</dict>
	</dict>

    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleURLName</key>
            <string>SalesforceOAuth2</string>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>swiftapp</string>
            </array>
        </dict>
    </array>

7.	Corrected several issues in libraries (most of them putting fulfill(()) instead of fulfill())

Finally it should work, but it simply shows me the story board


Best regards,
Andrey Manakov

**Comment by mike4aday** [comment]
@andrey-manakov by the way, your #7 (tuple arguments) is taken care of in the brand new (today) version 4.0.4.

Everything you did looks fine -- try calling a `salesforce` method in your view controller's `viewDidLoad` method. In the example, `loadData` queries Salesforce for task records. 

Once you make a call to Salesforce, Swiftly Salesforce will replace the current view controller from your storyboard with the Salesforce-hosted login form. Upon successful completion of authentication & authorization, Swiftly Salesforce will return the user to the replaced view controller.

**Comment by andrey-manakov** [comment]
Thanks! It worked for me finally. 

Regarding item 7 side question: where should I report small problems with compile which arise due to the swift changes (some of them in LockSmith, some in Alamofire, some in Swiftly)? And should I, would it help, or you anyway aware about them?

**Comment by mike4aday** [comment]
@andrey-manakov please open an issue. In case I'm not aware, would be good to know and remedy. Thanks.
