### ISSUE TITLE
ObjectDescription replacement?

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#48]
var DescribeAll : [String : ObjectDescription]!
 fails in 6.0

**Comment by mike4aday** [comment]
@pbrondum ObjectDescription became [ObjectMetadata](https://github.com/mike4aday/SwiftlySalesforce/blob/master/SwiftlySalesforce/Classes/ObjectMetadata.swift) in version 6.0

**Comment by pbrondum** [comment]
Thanks. 

Per
