### ISSUE TITLE
Even after successful pod install project does not run at all

### ISSUE THREAD

**Issue by nishiarya** [mike4aday/SwiftlySalesforce#51]
Hi,

I have created a blank project and successfully able to run pod 'SwiftlySalesforce' to download all the dependencies. All 5 dependencies download correctly and project workspace file created.

I opened workspace and did all setup in "Configure Your App Delegate for Salesforce also provided consumerKey and callback url" as per the instructions given in below link
https://github.com/mike4aday/SwiftlySalesforce

Then i have tried to run the app, app did not get run due to the downloaded dependancies errors which cannot be fixed manually at developer side.

Please see attached screenshots for refrance
![screen shot 2017-11-28 at 1 06 48 pm](https://user-images.githubusercontent.com/6350702/33308208-7f5eee90-d43f-11e7-8a08-a8f8fb47c27a.png)
![screen shot 2017-11-28 at 1 09 14 pm](https://user-images.githubusercontent.com/6350702/33308321-fbe81ed2-d43f-11e7-84c9-342f12b9d43c.png)
![screen shot 2017-11-28 at 1 09 59 pm](https://user-images.githubusercontent.com/6350702/33308336-0d65a9fe-d440-11e7-8dc9-f64a0f087c6a.png)
![screen shot 2017-11-28 at 1 36 45 pm](https://user-images.githubusercontent.com/6350702/33308622-39637c7e-d441-11e7-8614-f2984f421c21.png)

I have checked with both xcode versions 9.0 and 9.1.
Alamofire errors
Locksmith errors

I don't think we need to fix these errors manually.

Sample is running but through pod setup i am not able to use salesforce, instructions are waist if it can not work as expected.

I am blocked here now. Kindly provide me the solution so that i can attache latest Salesforce to my existing project through pods.

Thanks & Regards,
Nishant Singh

**Comment by mike4aday** [comment]
@nishiarya The current version of Swiftly Salesforce is v6.0, and it has only 1 dependency, PromiseKit. 
It seems you're using a much older version, 2.2.0, correct? Please upgrade your Podfile to use the latest version.

**Comment by nishiarya** [comment]
Oh! My bad, Thanks for the update.
