### ISSUE TITLE
bulk insert

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#54]
All salesforce.insert methods are single record. We've attempted bulk inserts, but get cut off after a small number of records.  What's the best way to bulk insert 100-1000 records?

Thanks

**Comment by mike4aday** [comment]
@pbrondum what do you mean by 'cut off'? What was the error(s)?

There are at least 3 options for 100-1000 records - the standard Salesforce REST API currently only supports 1 insert per call. (I will open an enhancement request for better support within Swiftly Salesforce for multi-record inserts that implements 1+ of the options below.)

1) Use `when(fulfilled:)` with an array of 100-1000 `insert` methods as the argument. Note that `when` is a `PromiseKit` method, so you'd need to import `PromiseKit` in your code (it is already included as the sole dependency of Swiftly Salesforce) and the inserted records must all be of the same type. You can see examples of `when` here: http://promisekit.org/docs/

2) Use Swiftly Salesforce's `Salesforce.custom` method with the composite API endpoint and build the payload yourself. The composite API only supports up to 25 inserts, so you'd probably need to bundle these together in a `when` as above. And each sub-request 'costs' 1 API call, so there is no quota savings from using the composite API. See: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_composite.htm

3) Use the `Salesforce.custom` method with the SOAP API endpoint to insert up to 200 records. I haven't tried this yet, so don't know for sure if it'd work.

If you are willing to poll for the asynchronous results, you could use the Bulk API to insert multiple records: https://resources.docs.salesforce.com/sfdc/pdf/api_asynch.pdf

**Comment by pbrondum** [comment]
Trying to insert 24 rows. See code below.  It inserts 3 records, log looks
likes everything is fine,  no error(s).  When I rotate the ALL_TEMPLTES
rows, it inserts either the first 3 or the last 3 rows.  ??

Per

 func readClientTemplates(id: String) {



        let ALL_TEMPLATES = [

            "TEXT_MESSAGES_BEFORE_Small",

            "TEXT_MESSAGES_BEFORE_Medium",

            "TEXT_MESSAGES_BEFORE_Large",

            "TEXT_MESSAGES_AFTER_Small",

            "TEXT_MESSAGES_AFTER_Medium",

            "TEXT_MESSAGES_AFTER_Large",

            "EMAIL_MESSAGES_BEFORE_Small",

            "EMAIL_MESSAGES_BEFORE_Medium",

            "EMAIL_MESSAGES_BEFORE_Large",

            "EMAIL_MESSAGES_AFTER_Small",

            "EMAIL_MESSAGES_AFTER_Medium",

            "EMAIL_MESSAGES_AFTER_Large",

            "SURVEY_MESSAGES_BEFORE_Small",

            "SURVEY_MESSAGES_BEFORE_Medium",

            "SURVEY_MESSAGES_BEFORE_Large",

            "SURVEY_MESSAGES_AFTER_Small",

            "SURVEY_MESSAGES_AFTER_Medium",

            "SURVEY_MESSAGES_AFTER_Large",

            "MEETING_AGENDAS_Small",

            "MEETING_AGENDAS_Medium",

            "MEETING_AGENDAS_Large",

            "TASK_TEMPLATE_Small",

            "TASK_TEMPLATE_Medium",

            "TASK_TEMPLATE_Large"]



        first {

            salesforce.identity()

            }.then {

                userInfo -> Promise<QueryResult<WiWoTemplate__c>> in

                guard userInfo.userID != "" else {

                    throw EventForceError.generic(code: 100, message: "Can't
determine user ID")

                }

                let soql = "SELECT
Name,TemplateNo__c,TemplateType__c,Version__c FROM WiWo_Template__c"

                return salesforce.query(soql: soql)

            }.then {

                (result: QueryResult<WiWoTemplate__c>) -> () in

                let WIWOTempl = result.records

                // Zero records.

                if WIWOTempl.count != 0 {

                    print("Existing records on server")

                    //  query the records

                    for WiWoRec in WIWOTempl {

                       ...

                    }

                    print("Found some server version (not the newest ness)
for \(self.templateName!) is \(self.templateVersion!) and no is \(self.
templateNo!)")

                } else {

                    // create the record

                    print("No records on server")

                    self.templateNo = 1

                    self.templateVersion = GLOBAL.templateVersion


                    for template in ALL_TEMPLATES {

                        let templateName = template

                        let fields = ["TemplateNo__c": self.templateNo!,
"Version__c": self.templateVersion!, "Name": templateName, "TemplateType__c"
: templateName] as [String : Encodable]

                        salesforce.insert(type: "WiWo_Template__c", fields:
fields)

                    }                 }

            }.always {

                // Stuff - not important

                print("In Always...")

            }.catch {

                // if SQL failed

                (error) -> () in

        }

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by mike4aday** [comment]
@pbrondum try creating an array of promises from `ALL_TEMPLATES` with `map` and then use that array as the argument to `when` -- something like this:

```swift
import PromiseKit
...
let promises = ALL_TEMPLATES.map {
    template in 
    let fields = ...
    return salesforce.insert(type: "WiWo_Template__c", fields: fields)
}
when(fulfilled: promises).then {
   // Do something with the results
}.catch {
  // Handle error
}
```

**Comment by pbrondum** [comment]
Thanks for the (better) code. Same result however. Turns out the problem
was a required field that was too small to hold the values. That explains
why only certain records worked and the error messages were not helpful.

Please close.

Thanks,

Per

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com
