### ISSUE TITLE
organization() does not return organization info

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#55]
Should the following not work? (a la identity())
first {        
        salesforce.organization()
      }.then {
            (org) -> Promise<Organization> in
            if let nameSpacePrefix = org.nameSpacePrefix {
                print("using namespaceprefix  \(nameSpacePrefix)")
            }
       }

**Comment by mike4aday** [comment]
@pbrondum what is the error? Is it a compile-time error? Your `then` is not returning a `Promise` so I believe the code will not compile as-is.

**Comment by pbrondum** [comment]
Isn't org() and organization() supposed to return information from the
organization object just like identity does for the user object?  Or am I
missing something?

Anyway, I'm trying to get nameSpacePrefix from organization() and it does
not return that info. It returns identity information.

Thanks,

Per

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by mike4aday** [comment]
@pbrondum would you post your code, and the results? 

Your understanding is largely correct. `org( )` returns the promise of an `Organization` struct; `identity( )` returns the promise of an `Identity` struct.

**Comment by pbrondum** [comment]
Since it looks like organization() uses identity(), and validates the
userid,

open func organization() -> Promise<Organization> {

return identity().then {

(identity: Identity) -> Promise<Organization> in

self.retrieve(type: "Organization", id: identity.orgID)

}

}

I assumed I should be able to do the following:

        first {

            // Get namespaceprefix of current user

            salesforce.organization()

        }.then {

            orgInfo -> Promise<QueryResult<AccountData>> in

            guard orgInfo.nameSpacePrefix != "" else {

                throw WiWoError.generic(code: 100, message: "Can't
determine nameSpacePrefix for user")
            }

I get the error: "Value of type 'Organization' has no member
'nameSpacePrefix'"

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by mike4aday** [comment]
@pbrondum is that a compile-time error? The correct property name is `Organization.namespacePrefix` -- first "p" is lower-case. See [Organization.swift](https://github.com/mike4aday/SwiftlySalesforce/blob/master/SwiftlySalesforce/Classes/Organization.swift)

`salesforce.organization()` calls `identity()` first in order to get the current user's org ID, and then it retrieves the `Organization` object for that ID.

**Comment by pbrondum** [comment]
In my code above. if you type orginfo. you get a list of Identity
properties, not organization properties. I don't think organization return
the expected properties.

 guard orgInfo.nameSpacePrefix != "" else {

                throw WiWoError.generic(code: 100, message: "Can't
determine nameSpacePrefix for user")
            }

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by mike4aday** [comment]
@pbrondum I will verify shortly. Does your code compile? The property is `namespacePrefix` (first "p" is lowercase). Also note that it is an optional string, so you probably want to test for nil, rather than for empty string.

**Comment by mike4aday** [comment]
@pbrondum I'm not able to reproduce that; `organization()` and `org()` are both returning a `Promise<Organization>` which is fulfilled correctly. I put a breakpoint on [line 730 in the test file](https://github.com/mike4aday/SwiftlySalesforce/blob/aa4bebaf972deb6f7ff935925d81ad92c79d8e3f/Example/Tests/SalesforceTests.swift#L730), and I do see the expected `Organization` struct.

**Comment by pbrondum** [comment]
Ok - error must be on my side then.  I'll try again tomorrow. Thanks for
looking into this.

Per

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com
