### ISSUE TITLE
 authData is not initialized when revoking

### ISSUE THREAD

**Issue by daichi1021** [mike4aday/SwiftlySalesforce#57]
Since authData has not been initialized when revoking, there is no way to check if the current session is valid after logout. Is it possible to set authData to nil when calling the logout method?

**Comment by mike4aday** [comment]
Thanks @daichi1021 - I'll look into this shortly.

**Comment by daichi1021** [comment]
Thank you!

If authData does not become nil, if it was offline at application startup, it was not possible to determine whether to proceed or not.

Even when there is time, we will be happy to respond.

**Comment by mike4aday** [comment]
@daichi1021 - thanks. This is implemented in the new v.6.0.2. The `authData` is cleared in the `revoke` method (see line 216 in [ConnectedApp.swift](https://github.com/mike4aday/SwiftlySalesforce/blob/master/SwiftlySalesforce/Classes/ConnectedApp.swift))
