### ISSUE TITLE
Close window

### ISSUE THREAD

**Issue by auctifera-josed** [mike4aday/SwiftlySalesforce#61]
Why doesn't the done button in the login page work? How can I close this window?

**Comment by mike4aday** [comment]
@auctifera-josed the login page is a web form hosted by Salesforce. The 'done' button essentially has no effect; it's not a modal browser window launched by a browser, as might be the case with authentication on a web app. You could create your own controller, as long as it implements `LoginViewController` protocol, but I don't know how/if you can hook into the 'done' button and react to it.

**Comment by auctifera-josed** [comment]
I was afraid of that, ok. Thank you for the quick reply.
