### ISSUE TITLE
Custom Branding login page not supported

### ISSUE THREAD

**Issue by abhijeetkokane** [mike4aday/SwiftlySalesforce#63]
• Login working fine when we using default login page
• When we use custom branding login page
• It loads the login url in SFSafariViewController properly, but after click on login its redirects me to chatter page in same window, which is incorrect flow.
• In case of default login page, it redirects me to my application, which is correct flow.
• For custom branding we are using vfx page in backend.
• I need to implement custom branding login in my application and navigate to my application after click on login
Kindly can you guys help me with this.
Thanks in advance ...

**Comment by mike4aday** [comment]
@abhijeetkokane are you referring to custom branded communities login? If so, see issue #3 - if not, please provide a short, but clear, code sample to illustrate the issue.

**Comment by abhijeetkokane** [comment]
Hi @mike4aday,

Thank you for your response. 
Yes, we are using “custom branding” for community login. Following is the code which we are using for invoking the login functionality:

public func login(url: URL) throws {

guard !loggingIn else {
throw SalesforceError.invalidity(message: "Already logging in!")
}

guard let window = UIApplication.shared.keyWindow else {
throw SalesforceError.invalidity(message: "No valid window!")
}

// Replace current root view controller with Safari view controller for login
let loginVC = SafariLoginViewController(url: url)
loginVC.replacedRootViewController = window.rootViewController
window.rootViewController = loginVC
}

Below is the code for handle the callback for reedit into the app after successful login:

/// Handles the redirect URL returned by Salesforce after OAuth2 authentication and authorization.
/// Restores the root view controller that was replaced by the Salesforce-hosted login web form
/// - Parameter url: URL returned by Salesforce after OAuth2 authentication & authorization
public func handleRedirectURL(url: URL) {

var result:LoginResult

// Note: docs are wrong - error information may be in URL fragment *or* in query string...
if let urlEncodedString = url.fragment ?? url.query, let authData = AuthData(urlEncodedString: urlEncodedString) {
result = .success(authData)
}
else {
// Can't make sense of the redirect URL
result = .failure(SalesforceError.unsupportedURL(url: url))
}
salesforce.authManager.loginCompleted(result: result)

// Restore the original root view controller
        ////************************************************************
        if let window = UIApplication.shared.keyWindow, let currentRootVC = window.rootViewController as? LoginViewController, let _ = currentRootVC.replacedRootViewController {
            
            let mainStoryboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
            let viewController = mainStoryboard.instantiateViewController(withIdentifier: "Home1")
            window.rootViewController = viewController
        }
}

I have noticed that, for login using default page, the callback method are getting invoked, but for the custom branding login page, the callback methods are not getting invoked.

**Comment by mike4aday** [comment]
@abhijeetkokane re. the code you included: is that the original Swiftly Salesforce code, or did you modify it? It's hard for me to tell if that is an as-is paste from Swiftly Salesforce source, or if you modified part(s). If modified, just include the modified segment(s).

Does the suggested workaround mentioned in issue #3 help?

**Comment by mike4aday** [comment]
@abhijeetkokane I'm closing this as no response - if it remains an issue, just reopen.

**Comment by abhijeetkokane** [comment]
Hi @mike4aday 

Sorry for not replying for a while, but we are still facing the same issue:

We have added following in your sample project on git:

Login host url - https://spacecommunity-developer-edition.ap7.force.com/mycommunity

Consumer Key 
3MVG9ZL0ppGP5UrCyn4nX.TOEnSFEhfQB8ntPSWhbgF_vr4AVm48FPHDSq561oMys7zqN8hA3I5qZ4AeetZAL

Consumer Secret 
7900526202222258945

Following are the login credentials:

Email : harshal@harshal.com
Password: aress123$

After login using above credentials, it is not getting redirected to iOS app.

Could you please help us and look into this. After successful login the control should redirect to iOS app.

**Comment by abhijeetkokane** [comment]
Hi @mike4aday

We have tried your solution but no luck so far.
The credentials that we have provided are sample credentials for you to check the issue once.

Could you please let us know are you able to navigate back to app after login.

**Comment by mike4aday** [comment]
@abhijeetkokane what is the callback URL configured in the connected app?

**Comment by abhijeetkokane** [comment]
We have set the callback URL - "sfdc://success"

**Comment by mike4aday** [comment]
@abhijeetkokane is this still an issue? Please try with new version 7 and re-open if there's still a problem.
