### ISSUE TITLE
Hiding login navigation bar or changing it's title.

### ISSUE THREAD

**Issue by unco182** [mike4aday/SwiftlySalesforce#75]
Hi everyone, 

I'm trying to find a way to hide the SFSafariViewController navigation bar or just changing it's title to something more nicer than a huge URL String (For example by "Login page"). But I'm not sure that there is a way to achieve this...

Is it possible right now ? 
Is there a way to PR that ? 

or is it juste forbidden by Apple Guideline to tweak these on SFSafariViewController ? 

Thanks in advance for your answers ! 
Cheers !

**Comment by mike4aday** [comment]
Hi @unco182 it's not possible as far as I know - or even desirable. See: https://stackoverflow.com/questions/48636741/how-to-change-sfsafariviewcontrollers-title-in-swift
