### ISSUE TITLE
Support for Chatter 

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#76]
It would be great to have easy access to Chatter (create, comment etc.) Alternatively, it would be awesome to get an example of using .custom to perform this.

**Comment by mike4aday** [comment]
@pbrondum in the newly-released version 7 you can create your own URLRequest and then pass it to `Salesforce.dataTask<T: Decodable>(with request: URLRequestConvertible)` - where `T` is your own `Decodable` model. (This replaces the former .custom resource.)
