### ISSUE TITLE
Swift 3.0 support

### ISSUE THREAD

**Issue by AshishAlva** [mike4aday/SwiftlySalesforce#8]
Supporting Swift 3.0 and latest dependencies (PromiseKit and LockSmith).

**Comment by Lufthummel** [comment]
Hi Ashish,
please look at my fork for Swift3 support: I was able to compile and run applications but the version still needs more testing. You can use Carthage, it will resolve dependencies to latest Alamofire & Promisekit. Swift3 is already on Master in this fork.

I know that Mike is working on it, he will incorporate the required changes soon.

**Comment by mike4aday** [comment]
Thanks @Lufthummel -- @AshishAlva I am working on updating Swiftly Salesforce to support Swift 3, and the corresponding updates to PromiseKit and LockSmith.

**Comment by mike4aday** [comment]
Swiftly Salesforce 3.0.0 released, includes support for Swift 3
