### ISSUE TITLE
Callback URL Usage

### ISSUE THREAD

**Issue by simonnarang** [mike4aday/SwiftlySalesforce#86]
Hi, I have my callback URL set to https://login.salesforce.com/services/oauth2/success however upon authorization my app does not open. If I set the callback to anything else, the OAuth website doesn't load. How should I fix this?

**Comment by mike4aday** [comment]
@simonnarang the callback URL must have a custom protocol, and **not** https, e.g. `myapp://success`

**Comment by mike4aday** [comment]
@simonnarang (continued) it doesn't actually matter what protocol you use, just be sure that the callback URL matches the callback URL defined in the Salesforce connected app, and that it has valid URL form.

**Comment by mike4aday** [comment]
@simonnarang closing this issue for now. Re-open or add comment if you still have question(s). Thanks.
