### ISSUE TITLE
Proactively checking limits

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#87]
I'm trying to be sensitive to the org's limits (API calls especially).  I looked at your limits App code, but that seems to be old (both where the info is stored and SWIFT version).  Would you be able to share the code for the new Limits app, or point me to where the information is stored (if not in Site)?

**Comment by mike4aday** [comment]
@pbrondum as you noted, the code in the Limits app [repo](https://github.com/mike4aday/LimitsForSalesforce) is out-of-date. The source for the new Limits app is not (currently) in a public repo. You can use the `limits` method [here](https://github.com/mike4aday/SwiftlySalesforce/blob/master/SwiftlySalesforce/Sources/Extensions/Salesforce+REST.swift#L71) to get the same information in your app with Swiftly Salesforce.

**Comment by pbrondum** [comment]
Excellent. Thank you. 

Per
