### ISSUE TITLE
group by SOQL and <SObject> 

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#88]
Having problems with a simple 'group by' soql statement when using <SObject>:
...
userInfo -> Promise<QueryResult<SObject>> in
let soql = "select accountid, count(id) from event group by accountId"
return salesforce.query(soql: soql)
}.then {
...
The query returns zero records, and fails with the following:
"The data couldn’t be read because it is missing.
Error: SOQL data query failed with code : keyNotFound(AttributeKeys(stringValue: "url", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "records", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key AttributeKeys(stringValue: \"url\", intValue: nil) (\"url\").", underlyingError: nil))"

**Comment by mike4aday** [comment]
@pbrondum I suspect this is a bug and the custom decoder doesn't handle grouped results. (Related to your issue #50). Will get this fixed as soon as I can.

**Comment by mike4aday** [comment]
@pbrondum BTW if you can't wait for the fix, you can create your own `Decodable` model class and use it instead of `QueryResult`.

**Comment by pbrondum** [comment]
My other workaround is multiple queries, but I love how you can issue
multiple different object queries in one call. So no rush...

Thanks

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com

**Comment by mike4aday** [comment]
Fixed in version 7.1.2

@pbrondum

**Comment by pbrondum** [comment]
Awesome!!!

Regards,

Per Jakobsen

Regular mail : perbrondum@gmail.com
Secure Mail: isper@protonmail.com
