### ISSUE TITLE
Winter '19 breaks 'identity'

### ISSUE THREAD

**Issue by mike4aday** [mike4aday/SwiftlySalesforce#91]
The date format of REST API 'id' endpoint  `last_modified_date` field changed:

Before Winter '19:  
`"last_modified_date" : "2018-06-16T15:40:38.000+0000"`

Winter '19:
`  "last_modified_date" : "2018-10-02T16:22:06Z"`

**Comment by mike4aday** [comment]
FYI @hmuronaka

**Comment by mike4aday** [comment]
https://releasenotes.docs.salesforce.com/en-us/winter19/release-notes/rn_security_auth_json_value_endpoints.htm

**Comment by auctifera-josed** [comment]
Hi, @mike4aday have you been able to work on this? Is this impacting only the latest version or all the previous versions also?

**Comment by mike4aday** [comment]
@auctifera-josed I'll have a fix shortly - aiming for today or tomorrow.
Seems that it impacts the `identity` endpoint only in Winter '19. I'll accommodate that first, and will check if the change to `User Info` has any impact, per the release notes:
https://releasenotes.docs.salesforce.com/en-us/winter19/release-notes/rn_security_auth_json_value_endpoints.htm

**Comment by mike4aday** [comment]
Fixed in version 7.1.1
FYI @auctifera-josed @hmuronaka
