### ISSUE TITLE
API documentation correction

### ISSUE THREAD

**Issue by pbrondum** [mike4aday/SwiftlySalesforce#96]
salesforce+SObject.swift refers to:
UIApplication.shared.registerForRemoteNotification() invocation.
should be:
UIApplication.shared.registerForRemoteNotifications() invocation.

**Comment by mike4aday** [comment]
Thanks @pbrondum - I'll take care of this shortly.

**Comment by mike4aday** [comment]
@pbrondum this has been corrected and is reflected in the documentation. Thanks for catching it.
http://mike4aday.github.io/SwiftlySalesforce/docs/Classes/Salesforce.html#/s:17SwiftlySalesforce0B0C24registerForNotifications11deviceToken7options10PromiseKit0I0CySSGSS_AC7OptionsVtF
